- repo: folke/tokyonight.nvim
- repo: iamcco/markdown-preview.nvim
  on_ft: [ markdown, pandoc.markdown, rmd ]
    #hook_add: |-
    #:!sh -c "cd app && yarn install;"
#- repo: itchyny/lightline.vim
#- repo: vim-airline/vim-airline
#- repo: glepnir/galaxyline.nvim
#- repo: glepnir/spaceline.vim
#- repo: liuchengxu/eleline.vim
